export const Images = {
  bgStart: require('../assets/img/bg/bg-start-6.5x.png'),
  bgNoStart: require('../assets/img/bg/bg-no-start-6.5x.png'),
  start: require('../assets/img/start/Start.png'),
  column: require('../assets/img/column/column.png'),
  coins: require('../assets/img/column/goldArtcoin.png'),
  hart: require('../assets/img/modal/hart.png'),
  bird1: require('../assets/img/bird/bird1.png'),
  bird2: require('../assets/img/bird/bird2.png'),
  bird3: require('../assets/img/bird/bird3.png'),
  bird4: require('../assets/img/bird/bonusBird1.png'),
  bird5: require('../assets/img/bird/crashBird1.png'),
  bird6: require('../assets/img/bird/crashBird2.png'),
  bird7: require('../assets/img/bird/crashBird3.png'),
};
